PKGDIR ?= ..
L4DIR  ?= $(PKGDIR)/../..

include $(L4DIR)/mk/Makeconf

# create examples demonstrating the use of your package in subdirectories
# and list those subdirs in the TARGET variable.
TARGET = dom0ClientServer

include $(L4DIR)/mk/subdir.mk
