PKGDIR          ?= ../..
L4DIR           ?= $(PKGDIR)/../..

TARGET           = dom0ClientServer
SRC_CC           = main.cc
SYSTEMS          = x86-l4f arm-l4f
REQUIRES_LIBS    = lwip dom0

include $(L4DIR)/mk/prog.mk
